version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - '5500:5500'
    restart: always
    networks:
      - monitor

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - monitor

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    networks:
      - monitor
    volumes:
      - grafana-storage:/var/lib/grafana

networks:
  monitor:

volumes:
  grafana-storage:
